<a href="https://colab.research.google.com/github/Nwosu-Ihueze/trax_sentiment_analysis/blob/main/trax2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
\from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [2]:
%cd /content/drive/MyDrive/trax_sentiment_analysis

/content/drive/MyDrive/trax_sentiment_analysis


In [3]:
!pip install trax

     |████████████████████████████████| 522kB 4.4MB/s 
     |████████████████████████████████| 153kB 6.8MB/s 
     |████████████████████████████████| 3.4MB 9.4MB/s 
     |████████████████████████████████| 61kB 5.8MB/s 
     |████████████████████████████████| 2.1MB 34.8MB/s 
     |████████████████████████████████| 3.9MB 33.8MB/s 
     |████████████████████████████████| 245kB 44.0MB/s 
     |████████████████████████████████| 1.2MB 54.4MB/s 
     |████████████████████████████████| 368kB 56.6MB/s 
     |████████████████████████████████| 901kB 45.5MB/s 
     |████████████████████████████████| 3.3MB 42.0MB/s 


In [4]:
import os 
import random as rnd


import trax
# set random seeds to make this notebook easier to replicate


# import trax.fastmath.numpy
import trax.fastmath.numpy as np

# import trax.layers
from trax import layers as tl

# import Layer from the utils.py file
from utils import Layer, load_tweets, process_tweet
#from utils import


[nltk_data] Downloading package twitter_samples to /root/nltk_data...
[nltk_data]   Unzipping corpora/twitter_samples.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [5]:
# Create an array using trax.fastmath.numpy
a = np.array(5.0)

# View the returned array
display(a)

print(type(a))

DeviceArray(5., dtype=float32)

<class 'jaxlib.xla_extension.DeviceArray'>


In [6]:
def f(x):
    
    # f = x^2
    return (x**2)

In [7]:
print(f"f(a) for a={a} is {f(a)}")

f(a) for a=5.0 is 25.0


In [8]:
grad_f = trax.fastmath.grad(fun=f)  # df / dx - Gradient of function f(x) with respect to x

# View the type of the retuned object (it's a function)
type(grad_f)

function

In [9]:
# Call the newly created function and pass in a value for x (the DeviceArray stored in 'a')
grad_calculation = grad_f(a)

# View the result of calling the grad_f function
display(grad_calculation)

DeviceArray(10., dtype=float32)

In [10]:
import numpy as np

# Load positive and negative tweets
all_positive_tweets, all_negative_tweets = load_tweets()

# View the total number of positive and negative tweets.
print(f"The number of positive tweets: {len(all_positive_tweets)}")
print(f"The number of negative tweets: {len(all_negative_tweets)}")

# Split positive set into validation and training
val_pos   = all_positive_tweets[4000:] # generating validation set for positive tweets
train_pos  = all_positive_tweets[:4000]# generating training set for positive tweets

# Split negative set into validation and training
val_neg   = all_negative_tweets[4000:] # generating validation set for negative tweets
train_neg  = all_negative_tweets[:4000] # generating training set for nagative tweets

# Combine training data into one set
train_x = train_pos + train_neg 

# Combine validation data into one set
val_x  = val_pos + val_neg

# Set the labels for the training set (1 for positive, 0 for negative)
train_y = np.append(np.ones(len(train_pos)), np.zeros(len(train_neg)))

# Set the labels for the validation set (1 for positive, 0 for negative)
val_y  = np.append(np.ones(len(val_pos)), np.zeros(len(val_neg)))

print(f"length of train_x {len(train_x)}")
print(f"length of val_x {len(val_x)}")

The number of positive tweets: 5000
The number of negative tweets: 5000
length of train_x 8000
length of val_x 2000


In [11]:
print("original tweet at training position 0")
print(train_pos[0])

print("Tweet at training position 0 after processing:")
process_tweet(train_pos[0])

original tweet at training position 0
#FollowFriday @France_Inte @PKuchly57 @Milipol_Paris for being top engaged members in my community this week :)
Tweet at training position 0 after processing:


['followfriday', 'top', 'engag', 'member', 'commun', 'week', ':)']

In [12]:
Vocab = {'__PAD__': 0, '__</e>__': 1, '__UNK__': 2} 

# Note that we build vocab using training data
for tweet in train_x: 
    processed_tweet = process_tweet(tweet)
    for word in processed_tweet:
        if word not in Vocab: 
            Vocab[word] = len(Vocab)
    
print("Total words in vocab are",len(Vocab))
display(Vocab)

Total words in vocab are 9092


{'__PAD__': 0,
 '__</e>__': 1,
 '__UNK__': 2,
 'followfriday': 3,
 'top': 4,
 'engag': 5,
 'member': 6,
 'commun': 7,
 'week': 8,
 ':)': 9,
 'hey': 10,
 'jame': 11,
 'odd': 12,
 ':/': 13,
 'pleas': 14,
 'call': 15,
 'contact': 16,
 'centr': 17,
 '02392441234': 18,
 'abl': 19,
 'assist': 20,
 'mani': 21,
 'thank': 22,
 'listen': 23,
 'last': 24,
 'night': 25,
 'bleed': 26,
 'amaz': 27,
 'track': 28,
 'scotland': 29,
 'congrat': 30,
 'yeaaah': 31,
 'yipppi': 32,
 'accnt': 33,
 'verifi': 34,
 'rqst': 35,
 'succeed': 36,
 'got': 37,
 'blue': 38,
 'tick': 39,
 'mark': 40,
 'fb': 41,
 'profil': 42,
 '15': 43,
 'day': 44,
 'one': 45,
 'irresist': 46,
 'flipkartfashionfriday': 47,
 'like': 48,
 'keep': 49,
 'love': 50,
 'custom': 51,
 'wait': 52,
 'long': 53,
 'hope': 54,
 'enjoy': 55,
 'happi': 56,
 'friday': 57,
 'lwwf': 58,
 'second': 59,
 'thought': 60,
 '’': 61,
 'enough': 62,
 'time': 63,
 'dd': 64,
 'new': 65,
 'short': 66,
 'enter': 67,
 'system': 68,
 'sheep': 69,
 'must': 70,
 'buy':

In [13]:
def tweet_to_tensor(tweet, vocab_dict, unk_token='__UNK__', verbose=False):
   
    word_l = process_tweet(tweet)
    
    if verbose:
        print("List of words from the processed tweet:")
        print(word_l)
        
   
    tensor_l = []
    
    unk_ID = vocab_dict[unk_token]
    
    if verbose:
        print(f"The unique integer ID for the unk_token is {unk_ID}")
        
    for word in word_l:
        
        word_ID = vocab_dict[word] if word in vocab_dict else unk_ID
   
        tensor_l.append(word_ID) 
    
    return tensor_l

In [14]:
print("Actual tweet is\n", val_pos[0])
print("\nTensor of tweet:\n", tweet_to_tensor(val_pos[0], vocab_dict=Vocab))

Actual tweet is
 Bro:U wan cut hair anot,ur hair long Liao bo
Me:since ord liao,take it easy lor treat as save $ leave it longer :)
Bro:LOL Sibei xialan

Tensor of tweet:
 [1065, 136, 479, 2351, 745, 8146, 1123, 745, 53, 2, 2672, 791, 2, 2, 349, 601, 2, 3489, 1017, 597, 4559, 9, 1065, 157, 2, 2]


In [15]:
def data_generator(data_pos, data_neg, batch_size, loop, vocab_dict, shuffle=False):
    
    assert batch_size % 2 == 0
    
    n_to_take = batch_size // 2
    
    pos_index = 0
    neg_index = 0
    
    len_data_pos = len(data_pos)
    len_data_neg = len(data_neg)
    
    pos_index_lines = list(range(len_data_pos))
    neg_index_lines = list(range(len_data_neg))
    
    if shuffle:
        rnd.shuffle(pos_index_lines)
        rnd.shuffle(neg_index_lines)
        
    stop = False
    
    while not stop:  
        
        batch = []
        
        for i in range(n_to_take):
                    
            if pos_index >= len_data_pos: 
                
                if not loop:
                    stop = True;
                    break;
                
                pos_index = 0
                
                if shuffle:
                
                    rnd.shuffle(pos_index_lines)
                    
           
            tweet = data_pos[pos_index_lines[pos_index]]
            
            tensor = tweet_to_tensor(tweet, vocab_dict)
            
            batch.append(tensor)
            
            
            pos_index = pos_index + 1

        for i in range(n_to_take):
            
            if neg_index >= len_data_neg:
                
                if not loop:
                    stop = True;
                    break;
                    
                neg_index = 0
                
                if shuffle:
            
                    rnd.shuffle(neg_index_lines)
            
            tweet = data_neg[neg_index_lines[neg_index]]
            
            tensor = tweet_to_tensor(tweet, vocab_dict)
            
            batch.append(tensor)
            
            neg_index += 1

        if stop:
            break;

        pos_index += n_to_take
        
        neg_index += n_to_take
        
        max_len = max([len(t) for t in batch]) 
        
        tensor_pad_l = []
        
        for tensor in batch:

            n_pad = max_len - len(tensor)
            
            pad_l = [0]*n_pad
            
            tensor_pad = tensor + pad_l
            
            
            tensor_pad_l.append(tensor_pad)

       
        inputs = np.array(tensor_pad_l)
  
        
        target_pos = [1]*n_to_take
        
        
        target_neg = [0]*n_to_take
        
       
        target_l = target_pos + target_neg
        
       
        targets = np.array(target_l)

        example_weights = np.ones_like(targets)
        

        yield inputs, targets, example_weights

In [16]:
rnd.seed(30) 

# Create the training data generator
def train_generator(batch_size, shuffle = False):
    return data_generator(train_pos, train_neg, batch_size, True, Vocab, shuffle)

# Create the validation data generator
def val_generator(batch_size, shuffle = False):
    return data_generator(val_pos, val_neg, batch_size, True, Vocab, shuffle)

# Create the validation data generator
def test_generator(batch_size, shuffle = False):
    return data_generator(val_pos, val_neg, batch_size, False, Vocab, shuffle)

# Get a batch from the train_generator and inspect.
inputs, targets, example_weights = next(train_generator(4, shuffle=True))

# this will print a list of 4 tensors padded with zeros
print(f'Inputs: {inputs}')
print(f'Targets: {targets}')
print(f'Example Weights: {example_weights}')

Inputs: [[2005 4451 3201    9    0    0    0    0    0    0    0]
 [4954  567 2000 1454 5174 3499  141 3499  130  459    9]
 [3761  109  136  583 2930 3969    0    0    0    0    0]
 [ 250 3761    0    0    0    0    0    0    0    0    0]]
Targets: [1 1 0 0]
Example Weights: [1 1 1 1]


In [17]:
class Relu(Layer):
    def forward(self, x):
       
        activation = np.maximum(x,0)

        
        return activation

In [18]:
from trax import fastmath

# use the numpy module from trax
np = fastmath.numpy

# use the fastmath.random module from trax
random = fastmath.random

In [19]:
tmp_key = random.get_prng(seed=1)
print("The random seed generated by random.get_prng")
display(tmp_key)

print("choose a matrix with 2 rows and 3 columns")
tmp_shape=(2,3)
display(tmp_shape)


tmp_weight = trax.fastmath.random.normal(key=tmp_key, shape=tmp_shape)

print("Weight matrix generated with a normal distribution with mean 0 and stdev of 1")
display(tmp_weight)

The random seed generated by random.get_prng


DeviceArray([0, 1], dtype=uint32)

choose a matrix with 2 rows and 3 columns


(2, 3)

Weight matrix generated with a normal distribution with mean 0 and stdev of 1


DeviceArray([[ 0.957307  , -0.9699291 ,  1.0070664 ],
             [ 0.36619025,  0.17294823,  0.29092228]], dtype=float32)

In [20]:
class Dense(Layer):

    # __init__ is implemented for you
    def __init__(self, n_units, init_stdev=0.1):
        
        # Set the number of units in this layer
        self._n_units = n_units
        self._init_stdev = 0.1

    # Please implement 'forward()'
    def forward(self, x):


        dense = np.dot(x, self.weights) 
        
        return dense

    # init_weights
    def init_weights_and_state(self, input_signature, random_key):
        

        input_shape = input_signature.shape

         
        w = self._init_stdev * random.normal(
            key = random_key, shape = (input_shape[-1], self._n_units))
        
        self.weights = w
        return self.weights

In [21]:
tmp_embed = tl.Embedding(vocab_size=3, d_feature=2)
display(tmp_embed)

Embedding_3_2

In [22]:

tmp_embed = np.array([[1,2,3,],
                    [4,5,6]
                   ])

# take the mean along axis 0
print("The mean along axis 0 creates a vector whose length equals the vocabulary size")
display(np.mean(tmp_embed,axis=0))

print("The mean along axis 1 creates a vector whose length equals the number of elements in a word embedding")
display(np.mean(tmp_embed,axis=1))

The mean along axis 0 creates a vector whose length equals the vocabulary size


DeviceArray([2.5, 3.5, 4.5], dtype=float32)

The mean along axis 1 creates a vector whose length equals the number of elements in a word embedding


DeviceArray([2., 5.], dtype=float32)

In [23]:
def classifier(vocab_size=len(Vocab), embedding_dim=256, output_dim=2, mode='train'):
        

    embed_layer = tl.Embedding(
        vocab_size=vocab_size, # Size of the vocabulary
        d_feature=embedding_dim)  # Embedding dimension
    
    # Create a mean layer, to create an "average" word embedding
    mean_layer = tl.Mean(axis=1)
    
    # Create a dense layer, one unit for each output
    dense_output_layer = tl.Dense(n_units = output_dim)

    
    # Create the log softmax layer (no parameters needed)
    log_softmax_layer = tl.LogSoftmax()
    
    
    model = tl.Serial(
      embed_layer,  # embedding layer
      mean_layer, # mean layer
      dense_output_layer, # dense output layer 
      log_softmax_layer # log softmax layer
    )  
    
    # return the model of type
    return model

In [24]:
from trax.supervised import training

batch_size = 16
rnd.seed(271)

train_task = training.TrainTask(
    labeled_data=train_generator(batch_size=batch_size, shuffle=True),
    loss_layer=tl.CrossEntropyLoss(),
    optimizer=trax.optimizers.Adam(0.01),
    n_steps_per_checkpoint=10,
)

eval_task = training.EvalTask(
    labeled_data=val_generator(batch_size=batch_size, shuffle=True),
    metrics=[tl.CrossEntropyLoss(), tl.Accuracy()],
)

model = classifier()

In [25]:
output_dir = '~/model/'
output_dir_expand = os.path.expanduser(output_dir)
print(output_dir_expand)

/root/model/


In [26]:
def train_model(classifier, train_task, eval_task, n_steps, output_dir):
    
    training_loop = training.Loop(
                                classifier,  # The learning model
                                train_task,  # The training task
                                eval_tasks = [eval_task], # The evaluation task
                                output_dir = output_dir,
                                ) # The output directory

    training_loop.run(n_steps = n_steps)

    # Return the training_loop, since it has the model.
    return training_loop

In [27]:
training_loop = train_model(model, train_task, eval_task, 100, output_dir_expand)


Step      1: Total number of trainable weights: 2328066
Step      1: Ran 1 train steps in 1.60 secs
Step      1: train CrossEntropyLoss |  0.69488102
Step      1: eval  CrossEntropyLoss |  0.68353546
Step      1: eval          Accuracy |  0.50000000

Step     10: Ran 9 train steps in 6.25 secs
Step     10: train CrossEntropyLoss |  0.64237189
Step     10: eval  CrossEntropyLoss |  0.58595258
Step     10: eval          Accuracy |  0.68750000

Step     20: Ran 10 train steps in 3.59 secs
Step     20: train CrossEntropyLoss |  0.44516355
Step     20: eval  CrossEntropyLoss |  0.28725046
Step     20: eval          Accuracy |  1.00000000

Step     30: Ran 10 train steps in 2.62 secs
Step     30: train CrossEntropyLoss |  0.22647271
Step     30: eval  CrossEntropyLoss |  0.14396974
Step     30: eval          Accuracy |  1.00000000

Step     40: Ran 10 train steps in 1.83 secs
Step     40: train CrossEntropyLoss |  0.14929722
Step     40: eval  CrossEntropyLoss |  0.10895798
Step     40: eva

In [28]:
tmp_train_generator = train_generator(16)

# get one batch
tmp_batch = next(tmp_train_generator)

# Position 0 has the model inputs (tweets as tensors)
# position 1 has the targets (the actual labels)
tmp_inputs, tmp_targets, tmp_example_weights = tmp_batch

print(f"The batch is a tuple of length {len(tmp_batch)} because position 0 contains the tweets, and position 1 contains the targets.") 
print(f"The shape of the tweet tensors is {tmp_inputs.shape} (num of examples, length of tweet tensors)")
print(f"The shape of the labels is {tmp_targets.shape}, which is the batch size.")
print(f"The shape of the example_weights is {tmp_example_weights.shape}, which is the same as inputs/targets size.")

The batch is a tuple of length 3 because position 0 contains the tweets, and position 1 contains the targets.
The shape of the tweet tensors is (16, 15) (num of examples, length of tweet tensors)
The shape of the labels is (16,), which is the batch size.
The shape of the example_weights is (16,), which is the same as inputs/targets size.


In [29]:
tmp_pred = training_loop.eval_model(tmp_inputs)
print(f"The prediction shape is {tmp_pred.shape}, num of tensor_tweets as rows")
print("Column 0 is the probability of a negative sentiment (class 0)")
print("Column 1 is the probability of a positive sentiment (class 1)")
print()
print("View the prediction array")
tmp_pred

The prediction shape is (16, 2), num of tensor_tweets as rows
Column 0 is the probability of a negative sentiment (class 0)
Column 1 is the probability of a positive sentiment (class 1)

View the prediction array


DeviceArray([[-8.4380684e+00, -2.1648407e-04],
             [-9.1697912e+00, -1.0395050e-04],
             [-8.4653263e+00, -2.1076202e-04],
             [-8.5329075e+00, -1.9693375e-04],
             [-6.3755035e+00, -1.7042160e-03],
             [-7.8908296e+00, -3.7431717e-04],
             [-8.8222256e+00, -1.4734268e-04],
             [-4.9443398e+00, -7.1492195e-03],
             [-2.4149418e-03, -6.0272913e+00],
             [-2.4948120e-03, -5.9947681e+00],
             [-3.6716461e-04, -7.9102879e+00],
             [-4.7683716e-07, -1.5010769e+01],
             [-8.7723732e-03, -4.7405248e+00],
             [-1.1200905e-03, -6.7948041e+00],
             [-2.3834705e-03, -6.0403881e+00],
             [-5.5360794e-04, -7.4992566e+00]], dtype=float32)

In [30]:
tmp_is_positive = tmp_pred[:,1] > tmp_pred[:,0]
for i, p in enumerate(tmp_is_positive):
    print(f"Neg log prob {tmp_pred[i,0]:.4f}\tPos log prob {tmp_pred[i,1]:.4f}\t is positive? {p}\t actual {tmp_targets[i]}")

Neg log prob -8.4381	Pos log prob -0.0002	 is positive? True	 actual 1
Neg log prob -9.1698	Pos log prob -0.0001	 is positive? True	 actual 1
Neg log prob -8.4653	Pos log prob -0.0002	 is positive? True	 actual 1
Neg log prob -8.5329	Pos log prob -0.0002	 is positive? True	 actual 1
Neg log prob -6.3755	Pos log prob -0.0017	 is positive? True	 actual 1
Neg log prob -7.8908	Pos log prob -0.0004	 is positive? True	 actual 1
Neg log prob -8.8222	Pos log prob -0.0001	 is positive? True	 actual 1
Neg log prob -4.9443	Pos log prob -0.0071	 is positive? True	 actual 1
Neg log prob -0.0024	Pos log prob -6.0273	 is positive? False	 actual 0
Neg log prob -0.0025	Pos log prob -5.9948	 is positive? False	 actual 0
Neg log prob -0.0004	Pos log prob -7.9103	 is positive? False	 actual 0
Neg log prob -0.0000	Pos log prob -15.0108	 is positive? False	 actual 0
Neg log prob -0.0088	Pos log prob -4.7405	 is positive? False	 actual 0
Neg log prob -0.0011	Pos log prob -6.7948	 is positive? False	 actual 0

In [31]:
print("Array of booleans")
display(tmp_is_positive)

# convert boolean to type int32
# True is converted to 1
# False is converted to 0
tmp_is_positive_int = tmp_is_positive.astype(np.int32)


# View the array of integers
print("Array of integers")
display(tmp_is_positive_int)

# convert boolean to type float32
tmp_is_positive_float = tmp_is_positive.astype(np.float32)

# View the array of floats
print("Array of floats")
display(tmp_is_positive_float)

Array of booleans


DeviceArray([ True,  True,  True,  True,  True,  True,  True,  True,
             False, False, False, False, False, False, False, False],            dtype=bool)

Array of integers


DeviceArray([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

Array of floats


DeviceArray([1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
             0.], dtype=float32)

In [32]:
tmp_pred.shape

(16, 2)

In [33]:
print(f"True == 1: {True == 1}")
print(f"True == 2: {True == 2}")
print(f"False == 0: {False == 0}")
print(f"False == 2: {False == 2}")

True == 1: True
True == 2: False
False == 0: True
False == 2: False


In [34]:
def compute_accuracy(preds, y, y_weights):
    
    is_pos =  preds[:, 1] > preds[:, 0] 

    # convert the array of booleans into an array of np.int32
    is_pos_int = is_pos.astype(np.int32)
    
    # compare the array of predictions (as int32) with the target (labels) of type int32
    correct = is_pos_int == y 

    # Count the sum of the weights.
    sum_weights = np.sum(y_weights)
    
    # convert the array of correct predictions (boolean) into an arrayof np.float32
    correct_float = correct.astype(np.float32)
    
    # Multiply each prediction with its corresponding weight.
    weighted_correct_float = correct_float * y_weights

    # Sum up the weighted correct predictions (of type np.float32), to go in the
    # denominator.
    weighted_num_correct = np.sum(weighted_correct_float)
 
    # Divide the number of weighted correct predictions by the sum of the
    # weights.
    accuracy = weighted_num_correct / sum_weights

    ### END CODE HERE ###
    return accuracy, weighted_num_correct, sum_weights

In [35]:
# test your function
tmp_val_generator = val_generator(64)

# get one batch
tmp_batch = next(tmp_val_generator)

# Position 0 has the model inputs (tweets as tensors)
# position 1 has the targets (the actual labels)
tmp_inputs, tmp_targets, tmp_example_weights = tmp_batch

# feed the tweet tensors into the model to get a prediction
tmp_pred = training_loop.eval_model(tmp_inputs)

tmp_acc, tmp_num_correct, tmp_num_predictions = compute_accuracy(preds=tmp_pred, y=tmp_targets, y_weights=tmp_example_weights)

print(f"Model's prediction accuracy on a single training batch is: {100 * tmp_acc}%")
print(f"Weighted number of correct predictions {tmp_num_correct}; weighted number of total observations predicted {tmp_num_predictions}")

Model's prediction accuracy on a single training batch is: 100.0%
Weighted number of correct predictions 64.0; weighted number of total observations predicted 64


In [36]:
def test_model(generator, model):
    
    accuracy = 0.
    total_num_correct = 0
    total_num_pred = 0
    
    for batch in generator: 
        
        # Retrieve the inputs from the batch
        inputs = batch[0]
        
        # Retrieve the targets (actual labels) from the batch
        targets = batch[1]
        
        # Retrieve the example weight.
        example_weight = batch[2]

        # Make predictions using the inputs
        pred = model(inputs)
        
        # Calculate accuracy for the batch by comparing its predictions and targets
        batch_accuracy, batch_num_correct, batch_num_pred = compute_accuracy(pred, targets, example_weight) 
        
        # Update the total number of correct predictions
        # by adding the number of correct predictions from this batch
        total_num_correct += batch_num_correct
        
        # Update the total number of predictions 
        # by adding the number of predictions made for the batch
        total_num_pred += batch_num_pred

    # Calculate accuracy over all examples
    accuracy = total_num_correct / total_num_pred
    
    return accuracy

In [37]:
def predict(sentence):
    inputs = np.array(tweet_to_tensor(sentence, vocab_dict=Vocab))
    
    # Batch size 1, add dimension for batch, to work with the model
    inputs = inputs[None, :]  
    
    # predict with the model
    preds_probs = model(inputs)
    
    # Turn probabilities into categories
    preds = int(preds_probs[0, 1] > preds_probs[0, 0])
    
    sentiment = "negative"
    if preds == 1:
        sentiment = 'positive'

    return preds, sentiment

In [38]:
sentence = "I love chicken"
tmp_pred, tmp_sentiment = predict(sentence)
print(f"The sentiment of the sentence \n***\n\"{sentence}\"\n***\nis {tmp_sentiment}.")

The sentiment of the sentence 
***
"I love chicken"
***
is positive.


In [39]:
sentence = "Stupidity disgusts me."
tmp_pred, tmp_sentiment = predict(sentence)
print(f"The sentiment of the sentence \n***\n\"{sentence}\"\n***\nis {tmp_sentiment}.")

The sentiment of the sentence 
***
"Stupidity disgusts me."
***
is negative.


In [40]:
from keras.models import Model
from tensorflow import keras

In [41]:
keras_layer = trax.AsKeras(model)

print(keras_layer)

In [42]:
import tensorflow as tf

In [43]:
inputs = tf.keras.Input(shape=(None,), dtype='int32')
hidden = keras_layer(inputs) 

outputs = hidden
keras_model = tf.keras.Model(inputs=inputs, outputs=outputs)
print(keras_model)

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: 
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert


AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.
AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.


AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.
AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.


In [44]:
import os

In [45]:
model_file = "/content/drive/MyDrive/trax_sentiment_analysis/trax.h5"
tf.saved_model.save(keras_model, model_file)

AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.
AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.
AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.
AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.


AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.
AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.
AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.


AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.


AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.
AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.
AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.
AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.


AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.
AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.
AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.
AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.


AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.
AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.
AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.
AssertShape cannot check shapes. This often happens when using trax2keras. Shape asserts are skipped.
INFO:tensorflow:Assets written to: /content/drive/MyDrive/trax_sentiment_analysis/trax.h5/assets


INFO:tensorflow:Assets written to: /content/drive/MyDrive/trax_sentiment_analysis/trax.h5/assets


In [46]:
loaded = tf.saved_model.load(model_file)

In [52]:
sentence = "he is tall."
tmp_pred, tmp_sentiment = predict(sentence)
print(f"The sentiment of the sentence \n***\n\"{sentence}\"\n***\nis {tmp_sentiment}.")

The sentiment of the sentence 
***
"he is tall."
***
is positive.
